### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1005]
The napari hub home page has stood the test of time since the hub was created 2 years ago. The home page has changed significantly a bit since the beginning with the addition of new features like npe2 metadata and categories, but overall the home page has mostly stayed the same.

Currently we're planning on updating the home page to improve discoverability. This ticket captures the work to accomplish that effort.

## Relevant Links

- [Designs](https://www.figma.com/file/MviVcecNZYJ6XB8QwpZAPu/Hub-Home-page-Reorg?node-id=605-29431&t=Pfl8Vnn9Q2XfNnkt-0)
- https://github.com/chanzuckerberg/napari-hub/issues/243

## Tasks

- [x] #1006
  - This will be a generic component used for both home page and plugin pages
  - [x] #1017
- [x] Search page updates
  - [x] #1007
  - [x] #1008
  - [x] #1035
  - [x] #1036
- [x] New plugins page
  - [x] #1009
  - [x] #1010
  - [x] #1011
- [x] Misc changes
  - [x] #1092
  - [x] #1037
  - [x] #1095
- [ ] Bugs
  - [x] #1122
  - [x] #1123
  - [x] #1135
  - [ ] #1138
  - [x] #1139
  - [x] #1140
  - [x] #1141 
  - [x] #1142
  - [ ] #1171
- [ ] Follow up work
  - [ ] #1161
  - [ ] #1162

**Comment by Janeece** [comment]
@codemonkey800 here's my review feedback on the hub home page. I've grouped feedback by page it applies to and they are roughly in order of importance inside that page group. I've added my prioritization on the feedback (see definitions below). 

It seems like a long list, but only two are what I'd consider possible blockers — happy to discuss the prioritization/what can be done with the time you have!

#### Prioritization Key:
-  **Must have:** blocker, highest priority feedback; implementation is broken or UX is compromised/confusing without update. 
- **Should have:** nonblocker, medium priority feedback; needed to fulfill design spec but not broken. 
- **Nice to have:** nonblocker, low priority feedback

----
### Global Nav
- [ ] **Must Have:** Navigation “Plugins” link should go to plugin/search page instead of home page. 

### Home page

- [ ]  **Should Have:** When I click something that will take me off of the home page (“Browse all”, “See All”, Plugin Card), home page goes into a loading state before changing pages; sometimes it takes a while. If there is loading needed, it’d be clearer for the user if they changed pages first, otherwise it feels broken. Speed improved after the first time but it was still happening. This is not a blocker but it is something that I’d encourage us to fix if possible. 

[homepage to search loading.webm](https://github.com/chanzuckerberg/napari-hub/assets/63013360/2b5a5308-2d37-4b06-a206-08e033404ff7)
[homepage to plugin page loading.webm](https://github.com/chanzuckerberg/napari-hub/assets/63013360/e8fe795f-d543-43c6-996a-5a097928466a)
- [ ] **Should Have:** Plugin Card (narrow screens) - increase spacing between description/name/details to 14px 
![homepage - plugin card mobile](https://github.com/chanzuckerberg/napari-hub/assets/63013360/d5e1d81f-68d7-4d34-a370-71035914b2eb)
- [ ] **Should Have:** Plugin type details should change with the type. Writer plugins should show what extensions it writes; Reader should show file extensions it reads. Currently all types show “Installs” 
![homepage - plugin type card details](https://github.com/chanzuckerberg/napari-hub/assets/63013360/84d54e9c-8eec-478f-92dc-7beac6c0534c)
- [ ]  **Should Have/Nice to have** - Icon for sample type should change with the type, currently shows “sample data” type icon with widget  (see [this page](https://www.figma.com/file/MviVcecNZYJ6XB8QwpZAPu/Hub-Home-page-Reorg?type=design&node-id=630%3A27348&mode=design&t=7cYKh99iSo3GTEzn-1) for the icons to pair with type) 
![homepage - Plugin type icon](https://github.com/chanzuckerberg/napari-hub/assets/63013360/f7a7bb55-39e1-4cc8-8ad3-bc728103923f)

### Plugin Page/Plugin Search
- [ ] **Must have:** “Clear all” in filters doesn’t work for desktop, but works on narrow screen. 
- [ ]  **Should Have:** tag styling updates/tag highlight when filter is active is missing. Filter tags should be primary200. Workflow/Modality tags should also be primary200 if their filter value is active.  
![search - tag styling](https://github.com/chanzuckerberg/napari-hub/assets/63013360/475f8c17-f927-438e-9e4f-fc1bc0b3de80)
- [ ] **Should Have:** on search page, narrow screen navigation’s hamburger icon should remain right aligned, even though search is hidden. 
![search mobile - nav](https://github.com/chanzuckerberg/napari-hub/assets/63013360/53ca2451-89fa-41e1-8566-79eae01915b8)
- [ ] **Should have:** on narrow screens, filter tag text is all caps, should match desktop title case. 
![search mobile - tag styling](https://github.com/chanzuckerberg/napari-hub/assets/63013360/638a4fb6-a8dc-418f-884f-697cca776838)
- [ ] **Nice to have:** on narrow/mobile screens, stack individual plugin listing content instead of 2 columns of content ([see design spec](https://www.figma.com/file/MviVcecNZYJ6XB8QwpZAPu/Hub-Home-page-Reorg?type=design&node-id=1109%3A30121&mode=design&t=7cYKh99iSo3GTEzn-1)) 
- [ ] **Nice to have:** reduce spacing between individual plugin listing content
![search mobile - style refinements](https://github.com/chanzuckerberg/napari-hub/assets/63013360/addbeb7a-ab97-41d2-8fd6-65a46efe0905)

**Comment by richaagarwal** [comment]
@codemonkey800 @junxini Curious if you think the remaining bugs & follow-up work are worth addressing now or leaving in the backlog. I'm going to close this epic out regardless as things look good & we launched yesterday!
