### ISSUE TITLE
make metadata from the npe1 & npe2 manifests available through the API

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#468]
### Job stories

_Primary Persona(s): napari developer, data analytics_

- [x]  When I'm writing a query to get plugins from napari, I can get the full manifest for any plugin on the napari hub so that I can implement new features in napari that rely on any metadata in the manifest file
- [x]  When I'm writing a query to get plugins from napari, I can identify which plugins support npe1 or npe2 so that I can measure and monitor npe2 adoption

### Tasks

- [x] Set up new AWS Lambda infrastructure in backend codebase to enable the containerized implementation for npe2
- [x] Ensure new AWS Lambda is set up in a way that aligns with security & infrastructure guidelines of the organization

**Comment by codemonkey800** [comment]
@klai95  @neuromusic For the frontend, we're expecting `npe2` data to look like this:

```ts
enum PluginType {
  Widget = 'widget',
  Reader = 'reader',
  Writer = 'writer',
  SampleData = 'sample_data',
  Theme = 'theme',
}

enum PluginWriterSaveLayer {
  Image = 'image',
  Points = 'points',
  Shapes = 'shapes',
}

interface NPE2Data {
  display_name: string;
  plugin_types?: PluginType[];
  reader_file_extensions?: string[];
  writer_file_extensions?: string[];
  writer_save_layers?: PluginWriterSaveLayer[];
}
```

Here's an example of data the frontend is expecting for each plugin data. This data should be available on the `/index` and `/plugin/<name>` APIs

```json5
{
  // Human readable display name
  display_name: 'Test Plugin',

  // Plugin types
  plugin_types: ['reader', 'writer'],

  // Reader open extensions
  reader_file_extensions: [
    'czi',
    'jpg',
    'pdf',
    'png',
    'psd',
    'tiff',
    'xcar',
    'zarr',
  ],

  // Writer save extensions
  writer_file_extensions: [
    'czi',
    'jpg',
    'pdf',
    'png',
    'psd',
    'tiff',
    'xcar',
    'zarr',
  ],

  // Writer save layers
  writer_save_layers: ['image', 'points', 'shapes'],
}
```

Ideally the backend should format the data the same to minimize additional work on the frontend. However, if we need to change up the interface for some reason then let me know and we can update the frontend interfaces in another PR

**Comment by richaagarwal** [comment]
I was going to create a new ticket to capture the work that was done to support legacy npe1 plugins, but after reviewing the information in this ticket again, it made most sense to update the title here (particularly since the work has already been in progress).  

To my knowledge, this is the additional work that wasn't originally a part of this ticket: 
1) It was discovered that only ~20% of plugins support np2, so a decision was made to expand the scope of this work to npe1 as well. However, providing npe1 metadata ended up being a non-trivial amount of work due to how lazy loading works in the npe1 shim. 
2) Additionally, plugin installations do not always succeed and thus, the user criteria to _"identify which plugins support npe1 or npe2"_ is slightly more complex, as there is a third possible value, which is that we do not know due to errors installing the plugin.  I know that work has been done to retry, keep track of the retry counts, and log the error messages - however based on my conversations with @neuromusic we are comfortable moving forward with not always providing a value here. I think there is still a decision that needs to be made in terms of what information the back-end passes to the front-end for those cases. I would suggest something like a `None` value, and then in future work explore doing more with the error messages, but I will let @klai95 and @codemonkey800 decide what's best here.

Please correct me if I got anything wrong here, and feel free to weigh in with additional details/context! I'm summarizing from recent conversations I've had, so I am sure there are details I am missing.

**Comment by neuromusic** [comment]
Related to the "third value" of install failures, I agree that `None` is sufficient for now. 

For some additional context, we know that users are struggling to install plugins, due to a combination of advanced pre-installation instructions and poor practices. @tlambert03 did a very nice exploration of installability last year: https://github.com/chanzuckerberg/napari-hub/discussions/334#discussioncomment-1748880. I think its high priority for us to improve the UX here, but that is definitely out of scope for this work.

**Comment by DragaDoncila** [comment]
@richaagarwal thank you for this summary! It is fairly comprehensive and indicative of the current state of things.

> However, providing npe1 metadata ended up being a non-trivial amount of work due to how lazy loading works in the npe1 shim.

I would just make a clarifying comment here that the lazy loading part was relatively easy to fix, really, and we're seeing comprehensive manifests for `npe1` plugins which we can install. The majority of the complexity really lies in the second part which is getting the installations to succeed and the plugin to be loaded for inspection. Part of this complexity is inherent (missing dependencies, compiled dependencies, etc.), but a lot of it is also due to the relatively slow iteration speed of having to redeploy to aws and wait for plugin info to be populated - we've tried testing locally as much as possible but, frustratingly, installations seem to work just fine in our local environments.

I would really love to have the full stack traces aggregated and written out somewhere for plugins that fail installation, so that we can run some quick analysis on typical failure reasons, and confidently split out those which are inherent to the plugin (which should roughly match Talley's list) and those which could be solved by us improving our aws image setup.

**Comment by tlambert03** [comment]
> However, providing npe1 metadata ended up being a non-trivial amount of work due to how lazy loading works in the npe1 shim.

I can definitely help here if you're trying to get metadata out of npe1 plugins.  You can force discovery using [`index_npe1_adapters`](https://github.com/napari/npe2/blob/main/npe2/_plugin_manager.py#L285) .  Let me know if you're still running into issues

**Comment by tlambert03** [comment]
oops... sorry, I just read @DragaDoncila's comment that this was an easy fix :) good.

**Comment by tlambert03** [comment]
From https://github.com/chanzuckerberg/napari-hub/issues/468#issuecomment-1112772660 ... it _kinda_ looks like you're prepping an API here that is not the same as the `schema.json` in npe2: https://github.com/napari/npe2/releases/download/v0.3.0/schema.json

is that the case?  It would be really awesome if you simply offered up the manifest as json, following the json schema spec at npe2.  can you clarify there?

**Comment by tlambert03** [comment]
ok, spoke with @DragaDoncila offline.  Sounds like the API mentioned above is mostly for backend-frontend communication at the hub, and that a full manifest will also be available.  That's great, thanks!  

So just to summarize, the two things we'd really like to have on the napari side are:
1. an endpoint to grab the complete manifest (in npe2 format) for one plugin
2. an endpoint to grab _all_ manifests for all plugins (in npe2 format)

**Comment by neuromusic** [comment]
@tlambert03 we'll have (1) with this chunk of work, but (2) will land later (probably with #546 )

**Comment by tlambert03** [comment]
dropping this here since @DragaDoncila mentioned that retrieving npe2 manifests from git repo's is still a bit challenging (sounds like you're trying to fully install stuff, which seems like it could easily be problematic):

```py
import os
import tempfile
from importlib.metadata import EntryPoint
from pathlib import Path
from subprocess import check_call

from npe2 import PluginManifest
from setuptools import Distribution
from setuptools.command.build_py import build_py


def get_npe2_manifest_from_repo(org: str, repo: str):
    """Clone repo from github into temporary directory"""
    url = f'https://github.com/{org}/{repo}.git'
    with tempfile.TemporaryDirectory() as tmpdir:
        os.chdir(tmpdir)
        check_call(['git', 'clone', url, tmpdir])
        dist = Distribution({'src_root': tmpdir})
        dist.parse_config_files()
        ep = dist.entry_points['napari.manifest'][0]
        match = EntryPoint.pattern.search(ep)
        assert match
        module = match.groupdict()['module']
        file = match.groupdict()['attr']
        builder = build_py(dist)
        builder.finalize_options()
        module_dir = Path(builder.get_package_dir(module))
        mf = PluginManifest.from_file(module_dir / file)
    return mf.json()
```

**Comment by richaagarwal** [comment]
This was released today! 🙌🏽 Shall we close this ticket and the corresponding epic?

**Comment by neuromusic** [comment]
did we miss the manifest endpoint?

e.g. https://api.napari-hub.org/plugins/stardist-napari/manifest doesn't resolve

**Comment by klai95** [comment]
> did we miss the manifest endpoint?
> 
> e.g. https://api.napari-hub.org/plugins/stardist-napari/manifest doesn't resolve

Per Ziyang's comment on Slack, the manifest endpoint would be https://api.napari-hub.org/manifest/stardist-napari  in this case.
