### ISSUE TITLE
Activity Dashboard to give insights into plugin quality

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#500]
### Summary

We plan to surface metrics on the activity related to usage and support of plugins on an “Activity Dashboard” for each plugin on the napari hub so that users can gain insight into the Quality of a plugin as evidenced through these metrics. 

### Outcome

Users will be able to gain insight into the quality of napari plugins better understanding how plugins are used and supported.

### How it will work

We will aggregate metrics from public sources, such as PyPI, Github, and image.sc, and display certain metrics on plugin listings under an "Activity" section. Where relevant, we will also surface prioritized metrics in other parts of the napari hub, such as plugin cards, sort and filter, or the revised landing page (e.g. a “trending” section)

### Assets

- [PRD](https://czi.quip.com/rloYAqqLEm59/PRD-Activity-Dashboard)

#### Frontend
- [x] https://github.com/chanzuckerberg/napari-hub/issues/586

#### Backend
- [x] https://github.com/chanzuckerberg/napari-hub/issues/638

### Stories

_Plugin Page Experience_

- [x] P0: https://github.com/chanzuckerberg/napari-hub/issues/664
- [x] P0: https://github.com/chanzuckerberg/napari-hub/issues/685
- [x] P0: #698
- [x] P0: #699
- [x] P0: #700
- [x] P0: #701
- [ ] P2: #704
- [ ] P2: #715 (<-- added by Lia)

_Search Page Experience_

- [ ] P1: #706
- [ ] P1: #707
- [x] P1: #705

**Comment by haesleinhuepf** [comment]
Consider adding `condastats` as data source as well. The picture drawn from conda download statistics and pypistats is not 100% consistent -> scientifically very interesting ;-)

See also
- https://github.com/haesleinhuepf/napari-pypistats/blob/main/conda_download_stats.ipynb

**Comment by neuromusic** [comment]
thanks @haesleinhuepf !! that's a great callout. tracking it here: https://github.com/chanzuckerberg/napari-hub/discussions/805
