### ISSUE TITLE
More robust failure handling for discovery of npe2 metadata

### ISSUE THREAD

**Issue by richaagarwal** [chanzuckerberg/napari-hub#587]
As a follow-up to https://github.com/chanzuckerberg/napari-hub/issues/468, we should create a more robust failure handling/retry system for when discovery of npe2 metadata fails, and move away from the current method of tracking `process_count` in the manifest files.

Note that the file creation trigger that would normally invoke the `plugins` lambda is currently disabled, due to issues that have come up (a possible infinite retry loop), draining our AWS resources. (TODO: Link to post-mortem doc). See https://github.com/chanzuckerberg/napari-hub/pull/583#discussion_r906392534 for a helpful write-up of the current architecture, and https://github.com/chanzuckerberg/napari-hub/pull/585 for the actual pull request that was merged in.

#### Technical considerations
- Using [SQS](https://aws.amazon.com/sqs/) has been suggested for handling retries
- We may also want to consider avoid retrying for now, if that makes sense as a quicker/interim step, and would allow us to at least get fresh data for plugins that aren't failing. e.g. for the step where discovery doesn't work, we do nothing (and perhaps with initial file creation, instead of putting in `process_count=0` we start with an empty file or some structured data indicating no metadata has been discovered).

**Comment by richaagarwal** [comment]
@klai95 Assigning you to this, with the assumption that we'll bring this into the sprint following HQ week! However, we may discuss briefly in sprint planning today / might be good to start thinking about how you'd want to architect this.

**Comment by DragaDoncila** [comment]
> We may also want to consider avoid retrying for now, if that makes sense as a quicker/interim step, and would allow us to at least get fresh data for plugins that aren't failing. e.g. for the step where discovery doesn't work, we do nothing

If part of this update includes using `npe2 fetch` to parse the manifests then I would be in favor of not retrying at all, to begin with, as the `npe2 fetch` command has been consistently & robustly retrieving manifests on first try. Given its robustness (and assuming our results are similar) we could long term decide to *only* retry if initial failure is caused by external reasons e.g. PyPI happens to be down when we attempt to access the URL or something like that.

**Comment by richaagarwal** [comment]
@DragaDoncila will write up sub-tasks, then we'll re-sync up on level of effort

**Comment by DragaDoncila** [comment]
Hi folks (@richaagarwal @neuromusic @klai95) , I've provided a rough update below for remaining open questions and TODOs wrt this work. The open questions will likely best be resolved by a live discussion where we can dive in a bit and weigh up the different options. Depending on what we decide there, the level of effort could change but we can talk through that as well. I think post discussion we can finalize a spec and pull out any issues we don't think need to be addressed in the current iteration. Let me know if you'd like me to expand on anything here!

 ### TODOs:
- [ ] Completely disable any retry mechanism
    - **Rationale**: based on the robustness of `npe2 fetch` implementation, inspection of error messages for failing plugins, and past experience we think it unlikely that discovery failures would be fixed on a retry, and thus a retry mechanism would be useful only in the case where we failed due to an external reason e.g. PyPI was temporarily down and we couldn't download the package. We can consider implementing a retry mechanism if monitoring reveals a need for it.
- [ ] Update lambda trigger to eliminate chance of infinite loop (see open question 1)
- [ ] Refactor `plugins/get_plugin_manifest.generate_manifest` to use `npe2 fetch` command (see open question 2)
    - **Rationale**: Following `npe2` [#185](https://github.com/napari/npe2/pull/185) the library now provides a `fetch` command which takes a plugin name and version, and retrieves its manifest (building it if the plugin is npe1). Using this tool is a good separation of concerns between the napari hub and the npe2 library, and ensures we use the same mechanisms a plugin developer would to ensure their plugin's compatibility with `npe2` and the napari hub. Additionally, the mechanism is more full featured than our initial implementation: avoids plugin installs for packages where the wheel can be retrieved, more options for customisation and error message reporting. 
- [ ] Add basic error capturing for manifests (see open question 4)
    - **Rationale**: Given past experience with integrity of `npe2` metadata we should be tracking the errors reported for each plugin. These can simply be tracked via an `error_message` field in the json attributes, but should ideally be tracked via a csv we can use for aggregate reporting (particularly given the homogeneity of error messages reported)
- [ ] Add tests
- [ ] Evaluate robustness

### Open questions
- [ ] 1. Reconsider trigger mechanism for lambda?
    - Easiest approach would be to still be writing some "trigger" file to s3 to invoke the lambda handler, but write the manifest to separate file (no danger of loop)
    - but there's definitely a better way to do this. We should investigate other triggers e.g. just directly invoking the lambda from the backend code, which should be doable
    - we could also consider not using a lambda at all, since `npe2 fetch` builds a dedicated isolated env before install - but we would then need to bring `npe2` dependency into backend (bigger refactor in general)
- [ ] 2. Decide on "togglable" features of `npe2 fetch` we may want (balancing complete metadata vs. doing sanity checks on the plugin):
    - install napari on initial failure in case plugin was missing `napari` dependency? (may need small npe2 change)
    - validate that `npe1` plugins can actually be imported before generating manifest? (may need small npe2 change)
    - catch missing dependency errors from plugin and attempt to fix?
- [ ] 3. Update preview page to use `npe2 fetch` command?
    - Pros: same mechanism, fuller featured, can provide error message
    - Will need update to `npe2 fetch` to use wheel if provided (should be trivial)
- [ ] 4. Level of error capturing
    - We can simply write the error message provided by `npe2 fetch` to each plugin (if we want to do aggregate reporting we can just query the hub API and go from there)
    - Alternatively we could write a csv somewhere in S3 (maybe expose it in future work) aggregating error messages for all plugins & versions. This would also provide a way for us to trivially schedule a retry e.g. once a week, for all plugins on the error list

**Comment by neuromusic** [comment]
thanks @draga!

regarding (2) I'm inclined to do as little guessing about what plugin developers indended to do (or should have done) but failed to do. that is... if napari needs to be imported for the plugin to load, then they should have specified it in their dependencies.

this is somewhat stringent and will result in a number of plugins with incomplete npe2 metadata, but we can address that through documention and implementing the updates you suggest in (3) to the Plugin Preview Page

**Comment by richaagarwal** [comment]
@DragaDoncila Thank you for this write-up!  If we completely disable any retry mechanism, then doesn't that eliminate the need for the failures plugin and thus eliminate the chance for an infinite loop? Or am I missing something there.

Happy to get you, Kevin and I in a meeting together to discuss more as well!

**Comment by DragaDoncila** [comment]
@richaagarwal yep, it does. Open question 1 is more about the fact that our trigger in that case would still be kinda "hacky" and definitely inelegant - do we want to tackle that now or are we happy with an inelegant solution is the question.

**Comment by richaagarwal** [comment]
@DragaDoncila Also, how do you feel about breaking out this work into several tickets - one for disabling the retry mechanism (and any code clean-up/removal/considerations that entails - I'll review the open questions in a bit), one for switching over to npe2 fetch, and one for the error capturing?  I see the error capturing as useful but not as critical as the first two, and I'd also like the PRs to be as small as possible.

**Comment by DragaDoncila** [comment]
@richaagarwal I can split them out definitely. I will say that minimally for the feature to be "live" again we would need to implement 1 and 2 in the TODOs: disable retry and update trigger mechanism. So I might put those together into one item.

**Comment by DragaDoncila** [comment]
I realized that I think I misunderstood this question:

> If we completely disable any retry mechanism, then doesn't that eliminate the need for the failures lambda and thus eliminate the chance for an infinite loop?

So let me expand a bit. The infinite loop danger comes from two places:
1. the fact that the failure handler triggers a retry
2. the fact that the standard handler **has to change the file that triggered it**

Disabling retries will address 1, but not 2. I had a look as to whether we can just *edit* the file to add the new content, rather than rewriting it, but afaict there is no such concept in aws. This means to avoid the infinite loop danger created by 2., we need to update the trigger mechanism too - minimally to create a different file to serve as the trigger e.g. we create "trigger.json" to serve as the trigger, but once we build the manifest we write to "manifest.json" and delete "trigger.json"

**Comment by richaagarwal** [comment]
> @richaagarwal I can split them out definitely. I will say that minimally for the feature to be "live" again we would need to implement 1 and 2 in the TODOs: disable retry and update trigger mechanism. So I might put those together into one item.

@DragaDoncila I think they should still be separate items. It's okay to have multiple tickets with their respective PRs needed to go "live" with something.

**Comment by richaagarwal** [comment]
@DragaDoncila I agree the current trigger mechanism isn't ideal (and having to delete and write a file each time an "edit" is needed is a consequence of choosing S3 storage for this -- we're hoping to explore moving over to a database but that won't be in scope for this current ticket).  

Could you say more about why introducing an npe2 dependency into the backend would require a bigger refactor? If that's too large of a lift, I agree that we should explore invoking the lambda directly from the lambda code, rather than having it triggered by S3 updates. 

We also need to decide whether we write an empty file if fetching isn't successful, or do nothing. I think we should no longer have to delete the file if we're not planning to re-try. But we should confirm with @neuromusic that we are comfortable with never re-trying for a given plugin/version for this phase of work.

**Comment by DragaDoncila** [comment]
> Could you say more about why introducing an npe2 dependency into the backend would require a bigger refactor?

Essentially if we decided the isolated env built by `npe2` was sufficient isolation for us not to be concerned about installing plugins, then we wouldn't need a separate lambda at all, so there'd be a bunch of code/config to remove and some things to tweak.

I suspect based on the notes in the tech spec that a separate image is necessary though, so I think you're right that invoking the `plugins` lambda from the backend code may be the way. I've been looking into it and I think I have a rough idea of what that would entail, but would still require a bit of exploration to make the proposal concrete.

> We also need to decide whether we write an empty file if fetching isn't successful, or do nothing. I think we should no longer have to delete the file if we're not planning to re-try. But we should confirm with @neuromusic that we are comfortable with never re-trying for a given plugin/version for this phase of work.

if we proceed with invoking the lambda directly then there would never be a need for an empty file or deleting/recreating. . We could also easily add a once weekly scheduled trigger or something to recheck the still failing plugins & retry (could come later). If we decide to keep the file creation trigger then I still think we wouldn't be deleting & recreating a file, but we *would* delete the spurious `trigger` file we created.

**Comment by richaagarwal** [comment]
@DragaDoncila If we don't store some kind of file for failures, it could get a little confusing which plugins we failed to discover, vs. which are new versions/new plugins that we haven't attempted discovery on yet. But I agree that we don't need some initial empty file for trigger purposes. 

Otherwise, that all sounds good. Thanks for looking into how to invoke the `plugins` lambda from the backend code!

**Comment by DragaDoncila** [comment]
> @DragaDoncila If we don't store some kind of file for failures, it could get a little confusing which plugins we failed to discover, vs. which are new versions/new plugins that we haven't attempted discovery on yet.

Oh yeah, totally. In my head I was assuming we would just keep that as one aggregate file e.g. via the error reporting. But yes, agreed, we need some flag for plugins we've already tried.
