### ISSUE TITLE
Migrate mailing list to HubSpot

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#643]
We would like to migrating the napari hub mailing list to HubSpot from MailChimp.

### Tasks
- [x] live prototype with hubspot form
- [x] Verify no cookies on napari-hub.org
- [x] Verify form is sending data to HubSpot
- [x] #663
- [ ] Create welcome email in HubSpot to send via automation when someone fills out the form (Kindra)
- [x] #644

**Comment by neuromusic** [comment]
@codemonkey800 has confirmed implementation works and does not introduce any new cookies.

Kindra will prep HubSpot configuration.

I've initiated a Trust XFN review to get updated copy for the Privacy page from Legal.

Once we have updated Privacy disclosure and HubSpot configured, we'll be ready to land #661
